-- Aura Crackers catalogue seed
-- 30 categories, 147 products
-- Safe to re-run: upserts by slug and keeps existing product images.

INSERT INTO categories (name, slug, description, is_active, sort_order)
SELECT
  v.name,
  v.slug,
  v.description,
  true,
  (SELECT COALESCE(MAX(sort_order), 0) FROM categories) + v.rn
FROM (
  VALUES
  ('Sound Party'::text, 'sound-party'::text, 'Loud festive sound crackers'::text, 1::integer),
  ('Cyclone Chakkars'::text, 'cyclone-chakkars'::text, 'Ground spinning chakkars'::text, 2::integer),
  ('Spin Win'::text, 'spin-win'::text, 'Spinners and spinning chakkars'::text, 3::integer),
  ('Drive Wheels'::text, 'drive-wheels'::text, 'Rotating wheel fireworks'::text, 4::integer),
  ('Flower Shower'::text, 'flower-shower'::text, 'Flower pot fountain crackers'::text, 5::integer),
  ('Colour Kotis'::text, 'colour-kotis'::text, 'Colourful koti crackers'::text, 6::integer),
  ('Triangle Fountain'::text, 'triangle-fountain'::text, 'Tri-colour fountain displays'::text, 7::integer),
  ('Twinkling Star'::text, 'twinkling-star'::text, 'Twinkling star sparklers'::text, 8::integer),
  ('Bitli Fizzly'::text, 'bitli-fizzly'::text, 'Bijili packs for celebrations'::text, 9::integer),
  ('Zoom Boom'::text, 'zoom-boom'::text, 'Bomb-style sound crackers'::text, 10::integer),
  ('Foil Bombs'::text, 'foil-bombs'::text, 'Foil bomb crackers'::text, 11::integer),
  ('Paper Blast'::text, 'paper-blast'::text, 'Paper blast packs'::text, 12::integer),
  ('Jet Rider'::text, 'jet-rider'::text, 'Rockets with aerial effects'::text, 13::integer),
  ('Crackling Torches'::text, 'crackling-torches'::text, 'Handheld crackling torches'::text, 14::integer),
  ('Rainbow Fountain'::text, 'rainbow-fountain'::text, 'Multicolour fountain mixes'::text, 15::integer),
  ('Shower Spark'::text, 'shower-spark'::text, 'Shower and novelty spark effects'::text, 16::integer),
  ('Kids Friendly'::text, 'kids-friendly'::text, 'Family-friendly novelty crackers'::text, 17::integer),
  ('Star Shooter'::text, 'star-shooter'::text, 'Shooter-style festive novelties'::text, 18::integer),
  ('Peacock Dance'::text, 'peacock-dance'::text, 'Peacock-themed visual crackers'::text, 19::integer),
  ('Fantastic Novelties'::text, 'fantastic-novelties'::text, 'Fun novelty fireworks'::text, 20::integer),
  ('Tun Tun Tun'::text, 'tun-tun-tun'::text, 'Fountain crackers with sparkling effects'::text, 21::integer),
  ('Midnight Magic Skyshots'::text, 'midnight-magic-skyshots'::text, 'Premium aerial skyshots'::text, 22::integer),
  ('Special Colour Skyshots'::text, 'special-colour-skyshots'::text, 'Colour-themed aerial skyshots'::text, 23::integer),
  ('Special Function Skyshots'::text, 'special-function-skyshots'::text, 'Special-effect aerial skyshots'::text, 24::integer),
  ('Premium Plus Brands'::text, 'premium-plus-brands'::text, 'Premium plus aerial series'::text, 25::integer),
  ('Aerial Multishots'::text, 'aerial-multishots'::text, 'Multi-shot aerial cakes'::text, 26::integer),
  ('Elite Setout & Fan Cake'::text, 'elite-setout-fan-cake'::text, 'Elite setout and fan cake displays'::text, 27::integer),
  ('Wonder Sparklers'::text, 'wonder-sparklers'::text, 'Electric and colour sparklers'::text, 28::integer),
  ('Colour Matches'::text, 'colour-matches'::text, 'Colour match packs'::text, 29::integer),
  ('Thunder'::text, 'thunder'::text, 'Thunder string crackers'::text, 30::integer)
) AS v(name, slug, description, rn)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  is_active = true,
  is_archived = false,
  archived_at = NULL;

INSERT INTO products (
  name,
  slug,
  category_id,
  description,
  specifications,
  price,
  pieces,
  stock_quantity,
  stock_alert_limit,
  brand,
  tag,
  is_available,
  is_featured,
  is_archived,
  sort_order
)
SELECT
  v.name,
  v.slug,
  c.id,
  v.description,
  v.specifications,
  v.price,
  v.pieces,
  v.stock_quantity,
  v.stock_alert_limit,
  v.brand,
  v.tag,
  true,
  v.is_featured,
  false,
  (SELECT COALESCE(MAX(sort_order), 0) FROM products) + v.rn
FROM (
  VALUES
  (
    '2¾" Kuruvi'::text,
    '2-3-4-inch-kuruvi'::text,
    'sound-party'::text,
    'Compact sound cracker for festive celebrations'::text,
    '{"Size":"2¾\"","Type":"Sound"}'::jsonb,
    80::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    1::integer
  ),
  (
    '3½" Lakshmi'::text,
    '3-1-2-inch-lakshmi'::text,
    'sound-party'::text,
    'Classic Lakshmi cracker with powerful sound'::text,
    '{"Size":"3½\"","Type":"Sound"}'::jsonb,
    100::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    2::integer
  ),
  (
    '4" Lakshmi'::text,
    '4-inch-lakshmi'::text,
    'sound-party'::text,
    'Popular Lakshmi cracker for festive occasions'::text,
    '{"Size":"4\"","Type":"Sound"}'::jsonb,
    130::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    3::integer
  ),
  (
    '4" Deluxe Lakshmi'::text,
    '4-inch-deluxe-lakshmi'::text,
    'sound-party'::text,
    'Deluxe Lakshmi cracker with enhanced performance'::text,
    '{"Size":"4\"","Type":"Sound"}'::jsonb,
    160::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    4::integer
  ),
  (
    '4" Gold Lakshmi'::text,
    '4-inch-gold-lakshmi'::text,
    'sound-party'::text,
    'Premium Lakshmi cracker for special celebrations'::text,
    '{"Size":"4\"","Type":"Premium Sound"}'::jsonb,
    180::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    5::integer
  ),
  (
    '5" Jallikattu'::text,
    '5-inch-jallikattu'::text,
    'sound-party'::text,
    'Powerful Jallikattu cracker for celebrations'::text,
    '{"Size":"5\"","Type":"Sound"}'::jsonb,
    220::numeric,
    10::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    6::integer
  ),
  (
    '6" Lion King'::text,
    '6-inch-lion-king'::text,
    'sound-party'::text,
    'Large sound cracker delivering exciting celebrations'::text,
    '{"Size":"6\"","Type":"Sound"}'::jsonb,
    280::numeric,
    10::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    7::integer
  ),
  (
    'Ground Chakkar Big (10 pcs)'::text,
    'ground-chakkar-big-10-pcs'::text,
    'cyclone-chakkars'::text,
    'Big spinning chakkar with sparkling effects'::text,
    '{"Type":"Ground Chakkar","Pack":"10 pcs"}'::jsonb,
    120::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    8::integer
  ),
  (
    'Ground Chakkar Special'::text,
    'ground-chakkar-special'::text,
    'cyclone-chakkars'::text,
    'Special chakkar creating bright spinning sparks'::text,
    '{"Type":"Ground Chakkar","Effect":"Sparks"}'::jsonb,
    100::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    9::integer
  ),
  (
    'Ground Chakkar Deluxe'::text,
    'ground-chakkar-deluxe'::text,
    'cyclone-chakkars'::text,
    'Deluxe chakkar with vibrant spinning effects'::text,
    '{"Type":"Ground Chakkar","Variant":"Deluxe"}'::jsonb,
    150::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    10::integer
  ),
  (
    'Spinner Special'::text,
    'spinner-special'::text,
    'spin-win'::text,
    'Special spinner producing colorful sparkling effects'::text,
    '{"Type":"Spinner","Effect":"Spinning Sparks"}'::jsonb,
    100::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    11::integer
  ),
  (
    'Spinner Deluxe'::text,
    'spinner-deluxe'::text,
    'spin-win'::text,
    'Deluxe spinner with brighter festive effects'::text,
    '{"Type":"Spinner","Variant":"Deluxe"}'::jsonb,
    140::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    12::integer
  ),
  (
    'Wine Chakkar Special'::text,
    'wine-chakkar-special'::text,
    'spin-win'::text,
    'Special chakkar with energetic spinning performance'::text,
    '{"Type":"Chakkar","Variant":"Special"}'::jsonb,
    120::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    13::integer
  ),
  (
    'Lotus Wheel (4 × 4)'::text,
    'lotus-wheel-4-x-4'::text,
    'drive-wheels'::text,
    'Lotus wheel delivering colorful spinning effects'::text,
    '{"Type":"Wheel","Size":"4 × 4"}'::jsonb,
    150::numeric,
    5::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    14::integer
  ),
  (
    'Disco Wheel'::text,
    'disco-wheel'::text,
    'drive-wheels'::text,
    'Disco wheel creating bright rotating visual effects'::text,
    '{"Type":"Wheel","Effect":"Rotating Sparks"}'::jsonb,
    130::numeric,
    5::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    15::integer
  ),
  (
    'Whistling Wheel'::text,
    'whistling-wheel'::text,
    'drive-wheels'::text,
    'Whistling wheel combining sound and motion'::text,
    '{"Type":"Wheel","Effect":"Whistling"}'::jsonb,
    150::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    16::integer
  ),
  (
    'Flower Pot Big'::text,
    'flower-pot-big'::text,
    'flower-shower'::text,
    'Large flower pot with sparkling fountain effects'::text,
    '{"Type":"Flower Pot","Size":"Big"}'::jsonb,
    180::numeric,
    5::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    17::integer
  ),
  (
    'Flower Pot Ashoka'::text,
    'flower-pot-ashoka'::text,
    'flower-shower'::text,
    'Ashoka flower pot producing colorful fountain effects'::text,
    '{"Type":"Flower Pot","Variant":"Ashoka"}'::jsonb,
    200::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    18::integer
  ),
  (
    'Colour Koti'::text,
    'colour-koti'::text,
    'colour-kotis'::text,
    'Colorful Koti cracker for festive celebrations'::text,
    '{"Type":"Koti","Effect":"Colour"}'::jsonb,
    100::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    19::integer
  ),
  (
    'Colour Koti DLX'::text,
    'colour-koti-dlx'::text,
    'colour-kotis'::text,
    'Deluxe Koti with vibrant colorful effects'::text,
    '{"Type":"Koti","Variant":"Deluxe"}'::jsonb,
    140::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    20::integer
  ),
  (
    'Super Koti (Jumbo)'::text,
    'super-koti-jumbo'::text,
    'colour-kotis'::text,
    'Jumbo Koti delivering impressive colorful effects'::text,
    '{"Type":"Koti","Variant":"Jumbo"}'::jsonb,
    180::numeric,
    10::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    21::integer
  ),
  (
    'Tri Colour'::text,
    'tri-colour'::text,
    'triangle-fountain'::text,
    'Three-color fountain with beautiful sparkling display'::text,
    '{"Type":"Fountain","Effect":"Three Colour"}'::jsonb,
    150::numeric,
    5::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    22::integer
  ),
  (
    'Tri Colour Spl'::text,
    'tri-colour-spl'::text,
    'triangle-fountain'::text,
    'Special tricolor fountain with vibrant effects'::text,
    '{"Type":"Fountain","Variant":"Special"}'::jsonb,
    180::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    23::integer
  ),
  (
    '½" Twinkling Star'::text,
    '1-2-inch-twinkling-star'::text,
    'twinkling-star'::text,
    'Small twinkling star with bright sparkling effect'::text,
    '{"Size":"½\"","Type":"Twinkling Star"}'::jsonb,
    80::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    24::integer
  ),
  (
    '4" Twinkling Star'::text,
    '4-inch-twinkling-star'::text,
    'twinkling-star'::text,
    'Large twinkling star with brilliant sparkling effects'::text,
    '{"Size":"4\"","Type":"Twinkling Star"}'::jsonb,
    150::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    25::integer
  ),
  (
    'Golden Bijili Red (50 pcs)'::text,
    'golden-bijili-red-50-pcs'::text,
    'bitli-fizzly'::text,
    'Red Bijili pack for festive celebrations'::text,
    '{"Pack":"50 pcs","Type":"Bijili"}'::jsonb,
    100::numeric,
    50::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    26::integer
  ),
  (
    'Golden Bijili Red (100 pcs)'::text,
    'golden-bijili-red-100-pcs'::text,
    'bitli-fizzly'::text,
    'Large red Bijili pack for celebrations'::text,
    '{"Pack":"100 pcs","Type":"Bijili"}'::jsonb,
    180::numeric,
    100::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    27::integer
  ),
  (
    'Golden Bijili Striped (100 pcs)'::text,
    'golden-bijili-striped-100-pcs'::text,
    'bitli-fizzly'::text,
    'Striped Bijili pack with festive appeal'::text,
    '{"Pack":"100 pcs","Type":"Bijili"}'::jsonb,
    200::numeric,
    100::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    28::integer
  ),
  (
    'King of King Bomb'::text,
    'king-of-king-bomb'::text,
    'zoom-boom'::text,
    'Premium bomb designed for powerful celebrations'::text,
    '{"Type":"Bomb","Variant":"King"}'::jsonb,
    180::numeric,
    10::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    29::integer
  ),
  (
    'Classic Bomb'::text,
    'classic-bomb'::text,
    'zoom-boom'::text,
    'Classic bomb for traditional festive celebrations'::text,
    '{"Type":"Bomb","Variant":"Classic"}'::jsonb,
    120::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    30::integer
  ),
  (
    'Digital Bomb'::text,
    'digital-bomb'::text,
    'zoom-boom'::text,
    'Digital bomb offering exciting festive effects'::text,
    '{"Type":"Bomb","Variant":"Digital"}'::jsonb,
    160::numeric,
    10::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    31::integer
  ),
  (
    'Bullet Bomb'::text,
    'bullet-bomb'::text,
    'foil-bombs'::text,
    'Bullet-style cracker for festive celebrations'::text,
    '{"Type":"Foil Bomb","Variant":"Bullet"}'::jsonb,
    120::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    32::integer
  ),
  (
    '555 Bomb'::text,
    '555-bomb'::text,
    'foil-bombs'::text,
    'Popular 555 bomb for festive occasions'::text,
    '{"Type":"Foil Bomb","Model":"555"}'::jsonb,
    150::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    33::integer
  ),
  (
    '¼ kg Paper Blast'::text,
    '1-4-kg-paper-blast'::text,
    'paper-blast'::text,
    'Compact paper blast pack for celebrations'::text,
    '{"Weight":"¼ kg","Type":"Paper Blast"}'::jsonb,
    150::numeric,
    1::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    34::integer
  ),
  (
    '½ kg Paper Blast'::text,
    '1-2-kg-paper-blast'::text,
    'paper-blast'::text,
    'Medium paper blast pack for celebrations'::text,
    '{"Weight":"½ kg","Type":"Paper Blast"}'::jsonb,
    280::numeric,
    1::integer,
    50::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    35::integer
  ),
  (
    '1 kg Paper Blast'::text,
    '1-kg-paper-blast'::text,
    'paper-blast'::text,
    'Large paper blast pack for celebrations'::text,
    '{"Weight":"1 kg","Type":"Paper Blast"}'::jsonb,
    500::numeric,
    1::integer,
    40::integer,
    8::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    36::integer
  ),
  (
    'Lunik Rocket'::text,
    'lunik-rocket'::text,
    'jet-rider'::text,
    'Classic rocket with exciting aerial performance'::text,
    '{"Type":"Rocket","Model":"Lunik"}'::jsonb,
    120::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    37::integer
  ),
  (
    'Whistling Rocket'::text,
    'whistling-rocket'::text,
    'jet-rider'::text,
    'Whistling rocket creating exciting aerial sounds'::text,
    '{"Type":"Rocket","Effect":"Whistling"}'::jsonb,
    150::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    38::integer
  ),
  (
    'Master Mix (3 in 1)'::text,
    'master-mix-3-in-1'::text,
    'crackling-torches'::text,
    'Three-in-one torch with colorful crackling effects'::text,
    '{"Pack":"3 in 1","Type":"Torch"}'::jsonb,
    150::numeric,
    3::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    39::integer
  ),
  (
    'Pop Corn Handle'::text,
    'pop-corn-handle'::text,
    'crackling-torches'::text,
    'Popcorn-style handle with sparkling crackling effects'::text,
    '{"Type":"Handle","Effect":"Crackling"}'::jsonb,
    120::numeric,
    5::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    40::integer
  ),
  (
    'Waterfall Handle'::text,
    'waterfall-handle'::text,
    'crackling-torches'::text,
    'Waterfall handle creating cascading sparkling effects'::text,
    '{"Type":"Handle","Effect":"Waterfall"}'::jsonb,
    150::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    41::integer
  ),
  (
    'Selfie Stick'::text,
    'selfie-stick'::text,
    'crackling-torches'::text,
    'Selfie-themed novelty with colorful festive effects'::text,
    '{"Type":"Novelty","Theme":"Selfie"}'::jsonb,
    150::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    42::integer
  ),
  (
    'Colour Smoke Handle'::text,
    'colour-smoke-handle'::text,
    'crackling-torches'::text,
    'Color smoke handle creating vibrant smoke effects'::text,
    '{"Type":"Handle","Effect":"Colour Smoke"}'::jsonb,
    160::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    43::integer
  ),
  (
    'Hili Mix (5 in 1) Multicolour'::text,
    'hili-mix-5-in-1-multicolour'::text,
    'rainbow-fountain'::text,
    'Five-in-one fountain with colorful visual effects'::text,
    '{"Pack":"5 in 1","Effect":"Multicolour"}'::jsonb,
    220::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    44::integer
  ),
  (
    'Nano Mix (5 in 1) Multicolour'::text,
    'nano-mix-5-in-1-multicolour'::text,
    'rainbow-fountain'::text,
    'Compact five-in-one multicolour fountain collection'::text,
    '{"Pack":"5 in 1","Effect":"Multicolour"}'::jsonb,
    200::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    45::integer
  ),
  (
    '4" Rainbow Mix'::text,
    '4-inch-rainbow-mix'::text,
    'rainbow-fountain'::text,
    'Four-inch fountain with colorful rainbow effects'::text,
    '{"Size":"4\"","Effect":"Rainbow"}'::jsonb,
    180::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    46::integer
  ),
  (
    'Star Pots (5 in 1)'::text,
    'star-pots-5-in-1'::text,
    'rainbow-fountain'::text,
    'Five-in-one star pots with sparkling effects'::text,
    '{"Pack":"5 in 1","Type":"Star Pots"}'::jsonb,
    250::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    47::integer
  ),
  (
    'Peacock Feathers'::text,
    'peacock-feathers'::text,
    'shower-spark'::text,
    'Peacock-inspired shower with beautiful sparkling effects'::text,
    '{"Type":"Shower Spark","Effect":"Peacock"}'::jsonb,
    180::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    48::integer
  ),
  (
    'Golden Ring'::text,
    'golden-ring'::text,
    'shower-spark'::text,
    'Golden ring effect with bright sparkling display'::text,
    '{"Type":"Shower Spark","Effect":"Golden Ring"}'::jsonb,
    160::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    49::integer
  ),
  (
    'Colour Rain'::text,
    'colour-rain'::text,
    'shower-spark'::text,
    'Color rain effect with vibrant festive display'::text,
    '{"Type":"Shower Spark","Effect":"Colour Rain"}'::jsonb,
    180::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    50::integer
  ),
  (
    'Tweet / Pop Mix'::text,
    'tweet-pop-mix'::text,
    'shower-spark'::text,
    'Fun mix combining tweet and pop effects'::text,
    '{"Type":"Mix","Effects":"Tweet, Pop"}'::jsonb,
    180::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    51::integer
  ),
  (
    'Dexter'::text,
    'dexter'::text,
    'shower-spark'::text,
    'Dexter-themed novelty for colorful celebrations'::text,
    '{"Type":"Novelty","Theme":"Dexter"}'::jsonb,
    150::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    52::integer
  ),
  (
    'Scooby Doo'::text,
    'scooby-doo'::text,
    'shower-spark'::text,
    'Scooby-themed novelty for festive celebrations'::text,
    '{"Type":"Novelty","Theme":"Scooby Doo"}'::jsonb,
    150::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    53::integer
  ),
  (
    'Powerpuff Girls'::text,
    'powerpuff-girls'::text,
    'shower-spark'::text,
    'Powerpuff-themed novelty with colorful festive effects'::text,
    '{"Type":"Novelty","Theme":"Powerpuff Girls"}'::jsonb,
    160::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    54::integer
  ),
  (
    'Dragon Ball 2 (Cocktail) (3 in 1)'::text,
    'dragon-ball-2-cocktail-3-in-1'::text,
    'shower-spark'::text,
    'Three-in-one Dragon Ball cocktail novelty'::text,
    '{"Pack":"3 in 1","Type":"Cocktail"}'::jsonb,
    220::numeric,
    3::integer,
    50::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    55::integer
  ),
  (
    'Assorted Cartoon'::text,
    'assorted-cartoon'::text,
    'kids-friendly'::text,
    'Assorted cartoon novelties for family celebrations'::text,
    '{"Type":"Novelty","Theme":"Cartoon"}'::jsonb,
    180::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    56::integer
  ),
  (
    'Shake Egg'::text,
    'shake-egg'::text,
    'kids-friendly'::text,
    'Fun egg-shaped novelty for festive enjoyment'::text,
    '{"Type":"Novelty","Shape":"Egg"}'::jsonb,
    120::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    57::integer
  ),
  (
    'Magic Pops'::text,
    'magic-pops'::text,
    'kids-friendly'::text,
    'Colorful magic pops for festive enjoyment'::text,
    '{"Type":"Novelty","Effect":"Colour"}'::jsonb,
    100::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    58::integer
  ),
  (
    'Chittu Puttu'::text,
    'chittu-puttu'::text,
    'kids-friendly'::text,
    'Fun novelty item for festive celebrations'::text,
    '{"Type":"Novelty","Category":"Kids"}'::jsonb,
    100::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    59::integer
  ),
  (
    'Gun'::text,
    'gun'::text,
    'kids-friendly'::text,
    'Novelty gun-themed product for festive enjoyment'::text,
    '{"Type":"Novelty","Theme":"Gun"}'::jsonb,
    120::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    60::integer
  ),
  (
    'Roll Cap'::text,
    'roll-cap'::text,
    'kids-friendly'::text,
    'Roll cap novelty for traditional festive fun'::text,
    '{"Type":"Cap","Format":"Roll"}'::jsonb,
    80::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    61::integer
  ),
  (
    'Ring Cap'::text,
    'ring-cap'::text,
    'kids-friendly'::text,
    'Ring cap novelty for traditional festive fun'::text,
    '{"Type":"Cap","Format":"Ring"}'::jsonb,
    80::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    62::integer
  ),
  (
    'Top Gun (5 in 1)'::text,
    'top-gun-5-in-1'::text,
    'star-shooter'::text,
    'Five-in-one shooter with exciting festive effects'::text,
    '{"Pack":"5 in 1","Type":"Shooter"}'::jsonb,
    220::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    63::integer
  ),
  (
    'AK-47'::text,
    'ak-47'::text,
    'star-shooter'::text,
    'AK-47 themed novelty for festive celebrations'::text,
    '{"Type":"Novelty Shooter","Theme":"AK-47"}'::jsonb,
    180::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    64::integer
  ),
  (
    'Phoenix Peacock'::text,
    'phoenix-peacock'::text,
    'peacock-dance'::text,
    'Peacock-themed product with colorful visual effects'::text,
    '{"Type":"Peacock","Effect":"Colour"}'::jsonb,
    220::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    65::integer
  ),
  (
    'Bada Peacock'::text,
    'bada-peacock'::text,
    'peacock-dance'::text,
    'Large peacock effect for festive celebrations'::text,
    '{"Type":"Peacock","Variant":"Big"}'::jsonb,
    250::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    66::integer
  ),
  (
    'Purple Peacock'::text,
    'purple-peacock'::text,
    'peacock-dance'::text,
    'Purple peacock effect with vibrant display'::text,
    '{"Type":"Peacock","Colour":"Purple"}'::jsonb,
    250::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    67::integer
  ),
  (
    'Blue Butterfly'::text,
    'blue-butterfly'::text,
    'fantastic-novelties'::text,
    'Butterfly novelty with colorful festive effects'::text,
    '{"Type":"Novelty","Theme":"Butterfly"}'::jsonb,
    120::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    68::integer
  ),
  (
    'I Cone'::text,
    'i-cone'::text,
    'fantastic-novelties'::text,
    'Cone novelty designed for festive enjoyment'::text,
    '{"Type":"Novelty","Format":"Cone"}'::jsonb,
    120::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    69::integer
  ),
  (
    'Spy Drone'::text,
    'spy-drone'::text,
    'fantastic-novelties'::text,
    'Drone-themed novelty for exciting celebrations'::text,
    '{"Type":"Novelty","Theme":"Drone"}'::jsonb,
    180::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    70::integer
  ),
  (
    'Lolly Pop'::text,
    'lolly-pop'::text,
    'fantastic-novelties'::text,
    'Lolly-themed novelty for festive enjoyment'::text,
    '{"Type":"Novelty","Theme":"Lolly Pop"}'::jsonb,
    100::numeric,
    5::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    71::integer
  ),
  (
    'Helicopter'::text,
    'helicopter'::text,
    'fantastic-novelties'::text,
    'Helicopter-themed novelty for festive celebrations'::text,
    '{"Type":"Novelty","Theme":"Helicopter"}'::jsonb,
    150::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    72::integer
  ),
  (
    'Mega Siren'::text,
    'mega-siren'::text,
    'fantastic-novelties'::text,
    'Siren-themed novelty with exciting festive effects'::text,
    '{"Type":"Novelty","Theme":"Siren"}'::jsonb,
    160::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    73::integer
  ),
  (
    'Magic Pots (Ganga Jamuna)'::text,
    'magic-pots-ganga-jamuna'::text,
    'fantastic-novelties'::text,
    'Magic pots producing colorful festive effects'::text,
    '{"Type":"Magic Pots","Variant":"Ganga Jamuna"}'::jsonb,
    200::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    74::integer
  ),
  (
    'Top Spinner (Bambolay)'::text,
    'top-spinner-bambolay'::text,
    'fantastic-novelties'::text,
    'Top spinner with energetic rotating effects'::text,
    '{"Type":"Spinner","Variant":"Bambolay"}'::jsonb,
    150::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    75::integer
  ),
  (
    'Money Bank'::text,
    'money-bank'::text,
    'fantastic-novelties'::text,
    'Money bank novelty for festive celebrations'::text,
    '{"Type":"Novelty","Theme":"Money Bank"}'::jsonb,
    150::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    76::integer
  ),
  (
    'Thor Car'::text,
    'thor-car'::text,
    'fantastic-novelties'::text,
    'Thor-themed car novelty for festive fun'::text,
    '{"Type":"Novelty","Theme":"Thor Car"}'::jsonb,
    180::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    77::integer
  ),
  (
    'Kuli Stick'::text,
    'kuli-stick'::text,
    'fantastic-novelties'::text,
    'Kuli stick novelty for festive celebrations'::text,
    '{"Type":"Novelty","Format":"Stick"}'::jsonb,
    120::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    78::integer
  ),
  (
    'Lemon Tree'::text,
    'lemon-tree'::text,
    'fantastic-novelties'::text,
    'Lemon-themed novelty with colorful festive effects'::text,
    '{"Type":"Novelty","Theme":"Lemon Tree"}'::jsonb,
    150::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    79::integer
  ),
  (
    'Colour Smoke Cylinder'::text,
    'colour-smoke-cylinder'::text,
    'fantastic-novelties'::text,
    'Color smoke cylinder producing vibrant smoke'::text,
    '{"Type":"Smoke","Effect":"Colour"}'::jsonb,
    180::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    80::integer
  ),
  (
    '4" Tila Fountain'::text,
    '4-inch-tila-fountain'::text,
    'tun-tun-tun'::text,
    'Four-inch fountain with bright sparkling effects'::text,
    '{"Size":"4\"","Type":"Fountain"}'::jsonb,
    150::numeric,
    5::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    81::integer
  ),
  (
    '5" Water Queen'::text,
    '5-inch-water-queen'::text,
    'tun-tun-tun'::text,
    'Five-inch fountain creating elegant visual effects'::text,
    '{"Size":"5\"","Type":"Fountain"}'::jsonb,
    200::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    82::integer
  ),
  (
    '6" Red Fountain'::text,
    '6-inch-red-fountain'::text,
    'tun-tun-tun'::text,
    'Six-inch red fountain with vibrant effects'::text,
    '{"Size":"6\"","Colour":"Red"}'::jsonb,
    250::numeric,
    5::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    83::integer
  ),
  (
    '7 Shots'::text,
    '7-shots'::text,
    'midnight-magic-skyshots'::text,
    'Seven-shot aerial display for festive celebrations'::text,
    '{"Shots":"7","Type":"Skyshot"}'::jsonb,
    350::numeric,
    1::integer,
    50::integer,
    10::integer,
    'Aura Crackers'::text,
    'Premium'::text,
    true::boolean,
    84::integer
  ),
  (
    '1" Prota Shots (3 in 1)'::text,
    '1-inch-prota-shots-3-in-1'::text,
    'midnight-magic-skyshots'::text,
    'Three-in-one skyshot with aerial effects'::text,
    '{"Size":"1\"","Pack":"3 in 1"}'::jsonb,
    300::numeric,
    3::integer,
    50::integer,
    10::integer,
    'Aura Crackers'::text,
    'Premium'::text,
    false::boolean,
    85::integer
  ),
  (
    '1¼" Chotta Sky Shot'::text,
    '1-1-4-inch-chotta-sky-shot'::text,
    'midnight-magic-skyshots'::text,
    'Compact skyshot with colorful aerial effects'::text,
    '{"Size":"1¼\"","Type":"Skyshot"}'::jsonb,
    280::numeric,
    1::integer,
    50::integer,
    10::integer,
    'Aura Crackers'::text,
    'Premium'::text,
    false::boolean,
    86::integer
  ),
  (
    '2" Rose Sky Shot'::text,
    '2-inch-rose-sky-shot'::text,
    'midnight-magic-skyshots'::text,
    'Rose-themed skyshot with colorful aerial effects'::text,
    '{"Size":"2\"","Effect":"Rose"}'::jsonb,
    400::numeric,
    1::integer,
    40::integer,
    8::integer,
    'Aura Crackers'::text,
    'Premium'::text,
    true::boolean,
    87::integer
  ),
  (
    '2" (3 in 1) Aerial Sky Shot'::text,
    '2-inch-3-in-1-aerial-sky-shot'::text,
    'midnight-magic-skyshots'::text,
    'Three-in-one aerial skyshot for celebrations'::text,
    '{"Size":"2\"","Pack":"3 in 1"}'::jsonb,
    450::numeric,
    3::integer,
    40::integer,
    8::integer,
    'Aura Crackers'::text,
    'Premium'::text,
    true::boolean,
    88::integer
  ),
  (
    '3½" GOT Series Sky Shots'::text,
    '3-1-2-inch-got-series-sky-shots'::text,
    'midnight-magic-skyshots'::text,
    'Premium GOT skyshot with aerial effects'::text,
    '{"Size":"3½\"","Series":"GOT"}'::jsonb,
    600::numeric,
    1::integer,
    40::integer,
    8::integer,
    'Aura Crackers'::text,
    'Premium'::text,
    true::boolean,
    89::integer
  ),
  (
    '4" Tin Sky Shots'::text,
    '4-inch-tin-sky-shots'::text,
    'midnight-magic-skyshots'::text,
    'Four-inch tin skyshot with colorful effects'::text,
    '{"Size":"4\"","Type":"Tin Skyshot"}'::jsonb,
    650::numeric,
    1::integer,
    35::integer,
    7::integer,
    'Aura Crackers'::text,
    'Premium'::text,
    false::boolean,
    90::integer
  ),
  (
    '4" Sky Shot (2 in 1)'::text,
    '4-inch-sky-shot-2-in-1'::text,
    'midnight-magic-skyshots'::text,
    'Two-in-one skyshot with vibrant aerial effects'::text,
    '{"Size":"4\"","Pack":"2 in 1"}'::jsonb,
    700::numeric,
    2::integer,
    35::integer,
    7::integer,
    'Aura Crackers'::text,
    'Premium'::text,
    true::boolean,
    91::integer
  ),
  (
    '5" Sky Shot (2 in 1)'::text,
    '5-inch-sky-shot-2-in-1'::text,
    'midnight-magic-skyshots'::text,
    'Large two-in-one skyshot for celebrations'::text,
    '{"Size":"5\"","Pack":"2 in 1"}'::jsonb,
    850::numeric,
    2::integer,
    30::integer,
    6::integer,
    'Aura Crackers'::text,
    'Premium'::text,
    true::boolean,
    92::integer
  ),
  (
    '3½" Blue Moon Sky Shot'::text,
    '3-1-2-inch-blue-moon-sky-shot'::text,
    'special-colour-skyshots'::text,
    'Blue moon skyshot with colorful aerial effects'::text,
    '{"Size":"3½\"","Colour":"Blue"}'::jsonb,
    550::numeric,
    1::integer,
    40::integer,
    8::integer,
    'Aura Crackers'::text,
    'Special Colors Skyshot'::text,
    true::boolean,
    93::integer
  ),
  (
    '3½" Pink Out Sky Shot'::text,
    '3-1-2-inch-pink-out-sky-shot'::text,
    'special-colour-skyshots'::text,
    'Pink skyshot creating bright aerial effects'::text,
    '{"Size":"3½\"","Colour":"Pink"}'::jsonb,
    550::numeric,
    1::integer,
    40::integer,
    8::integer,
    'Aura Crackers'::text,
    'Special Colors Skyshot'::text,
    true::boolean,
    94::integer
  ),
  (
    '3½" Purple Rain Sky Shot'::text,
    '3-1-2-inch-purple-rain-sky-shot'::text,
    'special-colour-skyshots'::text,
    'Purple rain skyshot with vibrant effects'::text,
    '{"Size":"3½\"","Colour":"Purple"}'::jsonb,
    550::numeric,
    1::integer,
    40::integer,
    8::integer,
    'Aura Crackers'::text,
    'Special Colors Skyshot'::text,
    true::boolean,
    95::integer
  ),
  (
    '4" Tiger Nagasala Falls'::text,
    '4-inch-tiger-nagasala-falls'::text,
    'special-function-skyshots'::text,
    'Tiger-themed skyshot with waterfall-style effects'::text,
    '{"Size":"4\"","Effect":"Falls"}'::jsonb,
    700::numeric,
    1::integer,
    35::integer,
    7::integer,
    'Aura Crackers'::text,
    'Special Function Skyshots'::text,
    true::boolean,
    96::integer
  ),
  (
    '4" Digital Crackling'::text,
    '4-inch-digital-crackling'::text,
    'special-function-skyshots'::text,
    'Digital crackling skyshot with bright effects'::text,
    '{"Size":"4\"","Effect":"Crackling"}'::jsonb,
    700::numeric,
    1::integer,
    35::integer,
    7::integer,
    'Aura Crackers'::text,
    'Special Function Skyshots'::text,
    true::boolean,
    97::integer
  ),
  (
    '4" 12 Step Sky Shot'::text,
    '4-inch-12-step-sky-shot'::text,
    'special-function-skyshots'::text,
    'Twelve-step skyshot with sequential aerial effects'::text,
    '{"Size":"4\"","Shots":"12"}'::jsonb,
    750::numeric,
    1::integer,
    35::integer,
    7::integer,
    'Aura Crackers'::text,
    'Special Function Skyshots'::text,
    true::boolean,
    98::integer
  ),
  (
    '4" Double Ball Sky Shot'::text,
    '4-inch-double-ball-sky-shot'::text,
    'special-function-skyshots'::text,
    'Double-ball skyshot with colorful aerial effects'::text,
    '{"Size":"4\"","Effect":"Double Ball"}'::jsonb,
    750::numeric,
    1::integer,
    35::integer,
    7::integer,
    'Aura Crackers'::text,
    'Special Function Skyshots'::text,
    true::boolean,
    99::integer
  ),
  (
    '3½" Satellite Series (2 in 1)'::text,
    '3-1-2-inch-satellite-series-2-in-1'::text,
    'premium-plus-brands'::text,
    'Two-in-one satellite skyshot with premium effects'::text,
    '{"Size":"3½\"","Pack":"2 in 1"}'::jsonb,
    700::numeric,
    2::integer,
    35::integer,
    7::integer,
    'Aura Crackers'::text,
    'Premium Plus'::text,
    true::boolean,
    100::integer
  ),
  (
    '4½" HD Series (2 in 1)'::text,
    '4-1-2-inch-hd-series-2-in-1'::text,
    'premium-plus-brands'::text,
    'HD two-in-one skyshot with premium effects'::text,
    '{"Size":"4½\"","Pack":"2 in 1"}'::jsonb,
    800::numeric,
    2::integer,
    30::integer,
    6::integer,
    'Aura Crackers'::text,
    'Premium Plus'::text,
    true::boolean,
    101::integer
  ),
  (
    '5" Train Series (2 in 1)'::text,
    '5-inch-train-series-2-in-1'::text,
    'premium-plus-brands'::text,
    'Train series skyshot with premium effects'::text,
    '{"Size":"5\"","Pack":"2 in 1"}'::jsonb,
    900::numeric,
    2::integer,
    30::integer,
    6::integer,
    'Aura Crackers'::text,
    'Premium Plus'::text,
    true::boolean,
    102::integer
  ),
  (
    '6" Plane Series (2 in 1)'::text,
    '6-inch-plane-series-2-in-1'::text,
    'premium-plus-brands'::text,
    'Plane series skyshot with premium effects'::text,
    '{"Size":"6\"","Pack":"2 in 1"}'::jsonb,
    1000::numeric,
    2::integer,
    25::integer,
    5::integer,
    'Aura Crackers'::text,
    'Premium Plus'::text,
    true::boolean,
    103::integer
  ),
  (
    '6" Pink Out'::text,
    '6-inch-pink-out'::text,
    'special-colour-skyshots'::text,
    'Six-inch pink skyshot with vibrant effects'::text,
    '{"Size":"6\"","Colour":"Pink"}'::jsonb,
    850::numeric,
    1::integer,
    30::integer,
    6::integer,
    'Aura Crackers'::text,
    'Special Colors Skyshot'::text,
    true::boolean,
    104::integer
  ),
  (
    '6" Blue Out'::text,
    '6-inch-blue-out'::text,
    'special-colour-skyshots'::text,
    'Six-inch blue skyshot with vibrant effects'::text,
    '{"Size":"6\"","Colour":"Blue"}'::jsonb,
    850::numeric,
    1::integer,
    30::integer,
    6::integer,
    'Aura Crackers'::text,
    'Special Colors Skyshot'::text,
    true::boolean,
    105::integer
  ),
  (
    '6" Purple Out'::text,
    '6-inch-purple-out'::text,
    'special-colour-skyshots'::text,
    'Six-inch purple skyshot with vibrant effects'::text,
    '{"Size":"6\"","Colour":"Purple"}'::jsonb,
    850::numeric,
    1::integer,
    30::integer,
    6::integer,
    'Aura Crackers'::text,
    'Special Colors Skyshot'::text,
    true::boolean,
    106::integer
  ),
  (
    '12 Shot – Tricolour Crackling Rider'::text,
    '12-shot-tricolour-crackling-rider'::text,
    'aerial-multishots'::text,
    'Twelve-shot rider with tricolour crackling effects'::text,
    '{"Shots":"12","Effect":"Tricolour Crackling"}'::jsonb,
    600::numeric,
    1::integer,
    40::integer,
    8::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    107::integer
  ),
  (
    '15 Shot – Smoke Shot'::text,
    '15-shot-smoke-shot'::text,
    'aerial-multishots'::text,
    'Fifteen-shot display with colorful smoke effects'::text,
    '{"Shots":"15","Effect":"Smoke"}'::jsonb,
    650::numeric,
    1::integer,
    40::integer,
    8::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    108::integer
  ),
  (
    '30 Shot (Multicolour & Crackling)'::text,
    '30-shot-multicolour-crackling'::text,
    'aerial-multishots'::text,
    'Thirty-shot display with multicolour crackling effects'::text,
    '{"Shots":"30","Effect":"Crackling"}'::jsonb,
    900::numeric,
    1::integer,
    30::integer,
    6::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    109::integer
  ),
  (
    '60 Shot (Multicolour & Crackling)'::text,
    '60-shot-multicolour-crackling'::text,
    'aerial-multishots'::text,
    'Sixty-shot display with multicolour crackling effects'::text,
    '{"Shots":"60","Effect":"Crackling"}'::jsonb,
    1500::numeric,
    1::integer,
    25::integer,
    5::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    110::integer
  ),
  (
    '120 Shot (Multicolour & Crackling)'::text,
    '120-shot-multicolour-crackling'::text,
    'aerial-multishots'::text,
    'Hundred-twenty-shot display with colorful effects'::text,
    '{"Shots":"120","Effect":"Crackling"}'::jsonb,
    2800::numeric,
    1::integer,
    20::integer,
    4::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    111::integer
  ),
  (
    '240 Shot (Multicolour & Crackling)'::text,
    '240-shot-multicolour-crackling'::text,
    'aerial-multishots'::text,
    'Large 240-shot display with colorful effects'::text,
    '{"Shots":"240","Effect":"Crackling"}'::jsonb,
    5000::numeric,
    1::integer,
    15::integer,
    3::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    112::integer
  ),
  (
    '30 Shot Peacock Dance'::text,
    '30-shot-peacock-dance'::text,
    'elite-setout-fan-cake'::text,
    'Peacock dance display with multiple sparkling effects'::text,
    '{"Shots":"30","Effect":"Peacock"}'::jsonb,
    1200::numeric,
    1::integer,
    30::integer,
    6::integer,
    'Aura Crackers'::text,
    'Elite Setout'::text,
    true::boolean,
    113::integer
  ),
  (
    '2¼" – 30 pcs Setout'::text,
    '2-1-4-inch-30-pcs-setout'::text,
    'elite-setout-fan-cake'::text,
    'Thirty-piece setout with colorful festive effects'::text,
    '{"Size":"2¼\"","Pack":"30 pcs"}'::jsonb,
    1500::numeric,
    30::integer,
    25::integer,
    5::integer,
    'Aura Crackers'::text,
    'Elite Setout'::text,
    true::boolean,
    114::integer
  ),
  (
    '3½" – 20 pcs Setout'::text,
    '3-1-2-inch-20-pcs-setout'::text,
    'elite-setout-fan-cake'::text,
    'Twenty-piece setout with premium visual effects'::text,
    '{"Size":"3½\"","Pack":"20 pcs"}'::jsonb,
    1800::numeric,
    20::integer,
    20::integer,
    4::integer,
    'Aura Crackers'::text,
    'Elite Setout'::text,
    true::boolean,
    115::integer
  ),
  (
    '10 × 10 (100 Shots)'::text,
    '10-x-10-100-shots'::text,
    'elite-setout-fan-cake'::text,
    'Hundred-shot setout for large celebrations'::text,
    '{"Format":"10 × 10","Shots":"100"}'::jsonb,
    2500::numeric,
    100::integer,
    20::integer,
    4::integer,
    'Aura Crackers'::text,
    'Elite Setout'::text,
    true::boolean,
    116::integer
  ),
  (
    '7 cm Electric Sparklers'::text,
    '7-cm-electric-sparklers'::text,
    'wonder-sparklers'::text,
    'Seven-centimeter sparklers with bright electric effects'::text,
    '{"Size":"7 cm","Type":"Electric"}'::jsonb,
    80::numeric,
    10::integer,
    150::integer,
    30::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    117::integer
  ),
  (
    '7 cm Colour Sparklers'::text,
    '7-cm-colour-sparklers'::text,
    'wonder-sparklers'::text,
    'Seven-centimeter sparklers producing colorful sparks'::text,
    '{"Size":"7 cm","Type":"Colour"}'::jsonb,
    90::numeric,
    10::integer,
    150::integer,
    30::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    118::integer
  ),
  (
    '7 cm Red Sparklers'::text,
    '7-cm-red-sparklers'::text,
    'wonder-sparklers'::text,
    'Seven-centimeter sparklers with red sparks'::text,
    '{"Size":"7 cm","Colour":"Red"}'::jsonb,
    90::numeric,
    10::integer,
    150::integer,
    30::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    119::integer
  ),
  (
    '7 cm Green Sparklers'::text,
    '7-cm-green-sparklers'::text,
    'wonder-sparklers'::text,
    'Seven-centimeter sparklers with green sparks'::text,
    '{"Size":"7 cm","Colour":"Green"}'::jsonb,
    90::numeric,
    10::integer,
    150::integer,
    30::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    120::integer
  ),
  (
    '10 cm Electric Sparklers'::text,
    '10-cm-electric-sparklers'::text,
    'wonder-sparklers'::text,
    'Ten-centimeter sparklers with bright electric effects'::text,
    '{"Size":"10 cm","Type":"Electric"}'::jsonb,
    100::numeric,
    10::integer,
    150::integer,
    30::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    121::integer
  ),
  (
    '10 cm Colour Sparklers'::text,
    '10-cm-colour-sparklers'::text,
    'wonder-sparklers'::text,
    'Ten-centimeter sparklers producing colorful sparks'::text,
    '{"Size":"10 cm","Type":"Colour"}'::jsonb,
    110::numeric,
    10::integer,
    150::integer,
    30::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    122::integer
  ),
  (
    '10 cm Red Sparklers'::text,
    '10-cm-red-sparklers'::text,
    'wonder-sparklers'::text,
    'Ten-centimeter sparklers with bright red sparks'::text,
    '{"Size":"10 cm","Colour":"Red"}'::jsonb,
    110::numeric,
    10::integer,
    150::integer,
    30::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    123::integer
  ),
  (
    '10 cm Green Sparklers'::text,
    '10-cm-green-sparklers'::text,
    'wonder-sparklers'::text,
    'Ten-centimeter sparklers with bright green sparks'::text,
    '{"Size":"10 cm","Colour":"Green"}'::jsonb,
    110::numeric,
    10::integer,
    150::integer,
    30::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    124::integer
  ),
  (
    '12 cm Electric Sparklers'::text,
    '12-cm-electric-sparklers'::text,
    'wonder-sparklers'::text,
    'Twelve-centimeter sparklers with electric sparkling effects'::text,
    '{"Size":"12 cm","Type":"Electric"}'::jsonb,
    120::numeric,
    10::integer,
    120::integer,
    25::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    125::integer
  ),
  (
    '12 cm Colour Sparklers'::text,
    '12-cm-colour-sparklers'::text,
    'wonder-sparklers'::text,
    'Twelve-centimeter sparklers with colorful sparkling effects'::text,
    '{"Size":"12 cm","Type":"Colour"}'::jsonb,
    130::numeric,
    10::integer,
    120::integer,
    25::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    126::integer
  ),
  (
    '12 cm Red Sparklers'::text,
    '12-cm-red-sparklers'::text,
    'wonder-sparklers'::text,
    'Twelve-centimeter sparklers producing red sparks'::text,
    '{"Size":"12 cm","Colour":"Red"}'::jsonb,
    130::numeric,
    10::integer,
    120::integer,
    25::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    127::integer
  ),
  (
    '12 cm Green Sparklers'::text,
    '12-cm-green-sparklers'::text,
    'wonder-sparklers'::text,
    'Twelve-centimeter sparklers producing green sparks'::text,
    '{"Size":"12 cm","Colour":"Green"}'::jsonb,
    130::numeric,
    10::integer,
    120::integer,
    25::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    128::integer
  ),
  (
    '15 cm Electric Sparklers'::text,
    '15-cm-electric-sparklers'::text,
    'wonder-sparklers'::text,
    'Fifteen-centimeter sparklers with electric effects'::text,
    '{"Size":"15 cm","Type":"Electric"}'::jsonb,
    150::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    129::integer
  ),
  (
    '15 cm Colour Sparklers'::text,
    '15-cm-colour-sparklers'::text,
    'wonder-sparklers'::text,
    'Fifteen-centimeter sparklers with colorful effects'::text,
    '{"Size":"15 cm","Type":"Colour"}'::jsonb,
    160::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    130::integer
  ),
  (
    '15 cm Red Sparklers'::text,
    '15-cm-red-sparklers'::text,
    'wonder-sparklers'::text,
    'Fifteen-centimeter sparklers producing red sparks'::text,
    '{"Size":"15 cm","Colour":"Red"}'::jsonb,
    160::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    131::integer
  ),
  (
    '15 cm Green Sparklers'::text,
    '15-cm-green-sparklers'::text,
    'wonder-sparklers'::text,
    'Fifteen-centimeter sparklers producing green sparks'::text,
    '{"Size":"15 cm","Colour":"Green"}'::jsonb,
    160::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    132::integer
  ),
  (
    '30 cm Electric Sparklers'::text,
    '30-cm-electric-sparklers'::text,
    'wonder-sparklers'::text,
    'Thirty-centimeter sparklers with electric sparkling effects'::text,
    '{"Size":"30 cm","Type":"Electric"}'::jsonb,
    220::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    133::integer
  ),
  (
    '30 cm Colour Sparklers'::text,
    '30-cm-colour-sparklers'::text,
    'wonder-sparklers'::text,
    'Thirty-centimeter sparklers with colorful effects'::text,
    '{"Size":"30 cm","Type":"Colour"}'::jsonb,
    230::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    134::integer
  ),
  (
    '30 cm Red Sparklers'::text,
    '30-cm-red-sparklers'::text,
    'wonder-sparklers'::text,
    'Thirty-centimeter sparklers producing red sparks'::text,
    '{"Size":"30 cm","Colour":"Red"}'::jsonb,
    230::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    135::integer
  ),
  (
    '30 cm Green Sparklers'::text,
    '30-cm-green-sparklers'::text,
    'wonder-sparklers'::text,
    'Thirty-centimeter sparklers producing green sparks'::text,
    '{"Size":"30 cm","Colour":"Green"}'::jsonb,
    230::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    136::integer
  ),
  (
    '50 cm Electric Sparklers'::text,
    '50-cm-electric-sparklers'::text,
    'wonder-sparklers'::text,
    'Long sparklers with bright electric effects'::text,
    '{"Size":"50 cm","Type":"Electric"}'::jsonb,
    300::numeric,
    10::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    137::integer
  ),
  (
    '50 cm Colour Sparklers'::text,
    '50-cm-colour-sparklers'::text,
    'wonder-sparklers'::text,
    'Long sparklers producing colorful sparkling effects'::text,
    '{"Size":"50 cm","Type":"Colour"}'::jsonb,
    320::numeric,
    10::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    138::integer
  ),
  (
    'Jio 50 (10 in 1)'::text,
    'jio-50-10-in-1'::text,
    'colour-matches'::text,
    'Ten-in-one colour match pack for celebrations'::text,
    '{"Pack":"10 in 1","Type":"Colour Match"}'::jsonb,
    100::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    139::integer
  ),
  (
    'Dot (10 in 1)'::text,
    'dot-10-in-1'::text,
    'colour-matches'::text,
    'Ten-in-one dot match pack for celebrations'::text,
    '{"Pack":"10 in 1","Type":"Match"}'::jsonb,
    100::numeric,
    10::integer,
    100::integer,
    20::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    140::integer
  ),
  (
    '28 Chorsa'::text,
    '28-chorsa'::text,
    'thunder'::text,
    'Chorsa thunder product for festive celebrations'::text,
    '{"Type":"Thunder","Variant":"28"}'::jsonb,
    180::numeric,
    10::integer,
    80::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    false::boolean,
    141::integer
  ),
  (
    '56 Giant'::text,
    '56-giant'::text,
    'thunder'::text,
    'Giant thunder product for festive celebrations'::text,
    '{"Type":"Thunder","Variant":"56"}'::jsonb,
    280::numeric,
    10::integer,
    70::integer,
    15::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    142::integer
  ),
  (
    '100 Thunder'::text,
    '100-thunder'::text,
    'thunder'::text,
    'Hundred-count thunder pack for festive celebrations'::text,
    '{"Count":"100","Type":"Thunder"}'::jsonb,
    450::numeric,
    100::integer,
    60::integer,
    10::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    143::integer
  ),
  (
    '1K Thunder'::text,
    '1k-thunder'::text,
    'thunder'::text,
    'Thousand-count thunder pack for celebrations'::text,
    '{"Count":"1K","Type":"Thunder"}'::jsonb,
    800::numeric,
    1000::integer,
    40::integer,
    8::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    144::integer
  ),
  (
    '2K Thunder'::text,
    '2k-thunder'::text,
    'thunder'::text,
    'Two-thousand-count thunder pack for celebrations'::text,
    '{"Count":"2K","Type":"Thunder"}'::jsonb,
    1500::numeric,
    2000::integer,
    30::integer,
    6::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    145::integer
  ),
  (
    '5K Thunder'::text,
    '5k-thunder'::text,
    'thunder'::text,
    'Five-thousand-count thunder pack for celebrations'::text,
    '{"Count":"5K","Type":"Thunder"}'::jsonb,
    3200::numeric,
    5000::integer,
    20::integer,
    4::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    146::integer
  ),
  (
    '10K Thunder'::text,
    '10k-thunder'::text,
    'thunder'::text,
    'Ten-thousand-count thunder pack for celebrations'::text,
    '{"Count":"10K","Type":"Thunder"}'::jsonb,
    6000::numeric,
    10000::integer,
    15::integer,
    3::integer,
    'Aura Crackers'::text,
    NULL::text,
    true::boolean,
    147::integer
  )
) AS v(
  name,
  slug,
  category_slug,
  description,
  specifications,
  price,
  pieces,
  stock_quantity,
  stock_alert_limit,
  brand,
  tag,
  is_featured,
  rn
)
JOIN categories c ON c.slug = v.category_slug
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  price = EXCLUDED.price,
  original_price = NULL,
  discount_percentage = NULL,
  pieces = EXCLUDED.pieces,
  stock_quantity = EXCLUDED.stock_quantity,
  stock_alert_limit = EXCLUDED.stock_alert_limit,
  brand = EXCLUDED.brand,
  tag = EXCLUDED.tag,
  is_available = true,
  is_featured = EXCLUDED.is_featured,
  is_archived = false,
  archived_at = NULL;
